version: '3.1'
services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
volumes:
  db: